"""Age-based CPU KV tiers: independent oracle, migration and atomic failures."""
import ctypes
import gc
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import sys
import unittest
from unittest.mock import patch
import weakref

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from compiler.importers.llama import import_llama_checkpoint
from compiler.planner.memory import MemoryBudgetError
from model_checkpoint_fixture import create_checkpoint
from q3_reference import decode_q3_row, quantize_q3_row
from runtime.nexapack.bundle import ModelBundleReader
from runtime.nexapack.format import NexaPackReader, decode_q4_row
from test_paged_transformer_regressions import _PagedFixture
from test_q4_paged_transformer_regressions import wide_bundle
from test_transformer_forward_regressions import random_bundle
from tiered_reference import TorchTieredReference, verify_tiered_bundle_forward
from transformer_reference import compare_logits, load_bundle_weights, torch_available


# Generated by TorchTieredReference + Python codecs before the runtime existed.
TIERED_GOLDEN = {
    "pack_sha256": "aeabc843eb9a1c4c72368351bb87ae681b5856c1e03bfd1462191c235b699df3",
    "token_chunks": [[1, 3], [5], [7]],
    "options": {"page_tokens": 1, "hot_pages": 1, "warm_pages": 1, "group_size": 3},
    "page_codecs": [["q4", "f32"], ["q3", "q4", "f32"], ["q3", "q3", "q4", "f32"]],
    "logits": [
        [-2.4955668449401855, -2.335420846939087, -1.800908088684082, -1.537189245223999,
         -1.262248158454895, 0.16082748770713806, 0.40964075922966003, 0.7235545516014099,
         0.5154129862785339, 0.8049032688140869, 1.0287563800811768, 1.2993520498275757,
         1.653331995010376, 1.7324328422546387, 1.0564872026443481, 1.2744392156600952],
        [-2.717005968093872, -2.7398428916931152, -1.0842905044555664, -1.150435209274292,
         -1.2381774187088013, -0.20467036962509155, -0.3342150151729584, -0.4485032856464386,
         0.07894039154052734, -0.04186752066016197, -0.1622001677751541, 0.6654370427131653,
         0.7226846814155579, 0.4107297360897064, 1.1553359031677246, 1.0539195537567139],
        [1.956418752670288, 1.9410736560821533, 1.4198280572891235, 1.3844279050827026,
         1.2854589223861694, 0.5280172228813171, 0.5009219646453857, 0.3477569818496704,
         -1.6758854389190674, -1.8107651472091675, -1.8619686365127563, -2.1864702701568604,
         -2.3031556606292725, -2.2741897106170654, -2.114018201828003, -2.127004861831665],
        [2.0037777423858643, 1.9869850873947144, 1.8033478260040283, 1.8046296834945679,
         1.774468183517456, 1.1418044567108154, 1.196305751800537, 1.1133038997650146,
         -1.4862079620361328, -1.5305804014205933, -1.542661428451538, -1.9317604303359985,
         -2.003661870956421, -1.911447286605835, -2.517198085784912, -2.488391160964966],
    ],
    "error_max": {"quantization_error": 0.44354209303855896,
                  "kv_quantization_error": 0.14667201042175293,
                  "combined_quantization_error": 0.44354209303855896},
}


class _TierFixture(_PagedFixture):
    def session(self, path=None, **options):
        from runtime.nexapack.tiered import TieredTransformerSession
        return TieredTransformerSession(
            path or self.path, memory_budget=options.pop("memory_budget", "1MiB"),
            max_sequence_length=options.pop("max_sequence_length", 8),
            page_tokens=options.pop("page_tokens", 2),
            kv_group_size=options.pop("kv_group_size", 3), **options)

    @staticmethod
    def codecs(session):
        return [page.codec for page in session._pages]

    @staticmethod
    def records(session, length=None):
        records = {}
        length = session.cache_length if length is None else length
        width, heads = session.config.head_dim, session.config.num_key_value_heads
        for position in range(length):
            index, within = divmod(position, session.page_tokens)
            page = session._pages[index]
            codec = page.codec
            if codec == "f32":
                row_bytes = 4 * width
            else:
                bits, group = (4 if codec == "q4" else 3), session.kv_group_size
                row_bytes = ((width + group - 1) // group) * (4 + (bits * group + 7) // 8)
            token_bytes = heads * row_bytes
            stride = (session.page_tokens * token_bytes + 63) // 64 * 64
            for layer in range(session.config.num_hidden_layers):
                for kind in range(2):
                    for head in range(heads):
                        address = page.address + (2 * layer + kind) * stride + within * token_bytes + head * row_bytes
                        records[layer, kind, position, head] = (codec, ctypes.string_at(address, row_bytes))
        return records

    def tiny_bundle(self):
        settings = json.loads((ROOT / "tests/fixtures/transformer_tiny_golden.json").read_text())
        source, path = self.directory / "source", self.directory / "tiny"
        create_checkpoint(source, include_tied_head=True)
        import_llama_checkpoint(source, path, **settings["import_settings"])
        return source, path


class TieredNativeRegressions(_TierFixture):
    def test_oracle_generated_golden_runs_without_torch(self):
        _, path = self.tiny_bundle()
        with ModelBundleReader(path) as bundle:
            hashes = {name: hashlib.sha256((path / entry["path"]).read_bytes()).hexdigest()
                      for name, entry in bundle.manifest["tensors"].items()}
        fingerprint = hashlib.sha256(json.dumps(hashes, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
        self.assertEqual(fingerprint, TIERED_GOLDEN["pack_sha256"])
        with self.session(path, page_tokens=1, hot_pages=1, warm_pages=1, max_chunk_length=2) as session:
            output = []
            for index, chunk in enumerate(TIERED_GOLDEN["token_chunks"]):
                output += session.prefill(chunk) if index == 0 else session.append(chunk)
                self.assertEqual(self.codecs(session), TIERED_GOLDEN["page_codecs"][index])
            self.assert_rows_close(output, TIERED_GOLDEN["logits"])

    def test_migration_occurs_after_logits_and_long_chunk_can_skip_warm(self):
        tokens = [1, 3, 5, 7, 2]
        expected = self.baseline(tokens)
        with self.session(page_tokens=1, hot_pages=1, warm_pages=1) as session:
            self.assert_rows_close(session.prefill(tokens), expected)
            self.assertEqual(self.codecs(session), ["q3", "q3", "q3", "q4", "f32"])
            self.assertEqual(session.token_ids, tuple(tokens))
        with self.session(page_tokens=2, hot_pages=1, warm_pages=0) as session:
            self.assert_rows_close(session.prefill(tokens), expected)
            self.assertEqual(self.codecs(session), ["q3", "q3", "f32"])

    def test_partial_newest_page_stays_f32_and_cold_prefix_is_never_reencoded(self):
        with self.session(page_tokens=2, hot_pages=1, warm_pages=1) as session:
            session.prefill([1, 3])
            self.assertEqual(self.codecs(session), ["f32"])
            session.decode(5)
            self.assertEqual(self.codecs(session), ["q4", "f32"])
            session.decode(7)
            self.assertEqual(self.codecs(session), ["q4", "f32"])
            session.decode(2)
            self.assertEqual(self.codecs(session), ["q3", "q4", "f32"])
            prefix = {key: value for key, value in self.records(session).items() if key[2] < 2}
            address = session._pages[0].address
            session.append([4, 6])
            self.assertEqual(self.codecs(session), ["q3", "q3", "q4", "f32"])
            self.assertEqual({key: value for key, value in self.records(session).items() if key[2] < 2}, prefix)
            self.assertEqual(session._pages[0].address, address)

    def test_q4_to_q3_uses_the_f32_bridge_from_current_packed_values(self):
        with self.session(page_tokens=1, hot_pages=1, warm_pages=1) as session:
            session.prefill([1, 3])
            before = {key: row for key, (codec, row) in self.records(session).items() if codec == "q4"}
            expected = {key: quantize_q3_row(decode_q4_row(row, session.config.head_dim, session.kv_group_size),
                                            session.kv_group_size) for key, row in before.items()}
            session.decode(5)
            after = self.records(session)
            self.assertTrue(expected)
            for key, row in expected.items():
                self.assertEqual(after[key], ("q3", row))

    def test_identical_chunk_history_repeats_and_different_boundaries_can_change_logits(self):
        _, path = self.tiny_bundle()
        tokens = [1, 3, 5, 7]
        with self.session(path, page_tokens=1) as all_at_once:
            whole = all_at_once.prefill(tokens)
        executions = []
        for _ in range(2):
            with self.session(path, page_tokens=1) as chunked:
                output = chunked.prefill(tokens[:2]) + chunked.append(tokens[2:3]) + chunked.append(tokens[3:])
                executions.append(output)
        self.assertEqual(executions[0], executions[1])
        self.assertGreater(max(abs(a - b) for left, right in zip(whole, executions[0]) for a, b in zip(left, right)), 0.01)

    def test_budget_rejects_before_native_and_payload_and_accepts_exact_bound(self):
        with self.session() as session:
            bound = session.report()["memory"]["capacity_managed_buffers_bound_bytes"]
        with patch("runtime.nexapack.transformer._load_kernels", side_effect=AssertionError("native load")), \
             patch.object(NexaPackReader, "read_rows_into", side_effect=AssertionError("payload")), \
             patch.object(ModelBundleReader, "read_f32_into", side_effect=AssertionError("norm payload")):
            with self.assertRaises(MemoryBudgetError):
                self.session(memory_budget=bound - 1)
        with self.session(memory_budget=bound) as exact:
            exact.prefill([1, 3, 5])
            exact.append([7, 2])
            self.assertLessEqual(exact.report()["memory"]["managed_buffers_peak_bound_bytes"], bound)

    def test_physical_memory_and_migration_stats_include_padding_and_old_sources(self):
        path = self.directory / "wide"
        wide_bundle(path)
        with self.session(path, page_tokens=2, hot_pages=1, warm_pages=1, kv_group_size=32) as session:
            session.prefill([1, 3, 5, 7, 2, 4, 6, 8])
            report = session.report()
            memory, migration = report["memory"], report["kv_migration"]
            # D64/P2: F32=1087 B, Q4=319 B, Q3=191 B per whole page,
            # including two aligned K/V buffers and 63 B base-alignment slack.
            self.assertEqual(self.codecs(session), ["q3", "q3", "q4", "f32"])
            self.assertEqual(session.resident_kv_bytes, 2 * 191 + 319 + 1087)
            self.assertEqual(memory["kv_resident_allocation_bytes"], session.resident_kv_bytes)
            self.assertEqual(memory["kv_attention_phase_pages_bytes"], 4 * 1087)
            self.assertEqual(memory["kv_transaction_peak_allocation_bytes"], 4 * 1087 + 2 * 191 + 319)
            self.assertEqual(memory["managed_buffers_peak_bound_bytes"],
                             max(memory["kv_attention_phase_bound_bytes"], memory["kv_migration_phase_bound_bytes"]))
            self.assertLess(session.resident_kv_bytes, 4 * 1087)
            self.assertEqual(migration["pages_reencoded"], 3)
            self.assertEqual(migration["source_bytes"], 3072)
            self.assertEqual(migration["target_bytes"], 416)
            self.assertEqual(migration["value_count"], 768)
            self.assertGreater(migration["max_abs_error"], 0)
            self.assertAlmostEqual(migration["rmse"] ** 2, migration["sum_squared_error"] / 768)
            self.assertEqual(report["io"]["kv_pages_allocated"], 7)
            self.assertEqual(report["io"]["kv_prefix_bytes_copied"], 0)
            self.assertEqual(memory["kv_full_dequantized_buffer_bytes"], 0)

    def test_failed_report_keeps_old_pages_bytes_tokens_and_report_with_retained_traceback(self):
        errors, references = [], []
        with self.session(page_tokens=1) as session:
            session.prefill([1, 3, 5])
            old_records, old_report = self.records(session), session.report()
            old_tokens, old_pages = session.token_ids, tuple(session._pages)
            allocate = session._allocate_page
            def track(*args, **kwargs):
                page = allocate(*args, **kwargs)
                references.append((weakref.ref(page), weakref.ref(page.arena)))
                return page
            report = session._report
            def fail_report(*args, **kwargs):
                if kwargs.get("executed"):
                    raise RuntimeError("report creation failed")
                return report(*args, **kwargs)
            with patch.object(session, "_allocate_page", track), patch.object(session, "_report", fail_report):
                try:
                    session.append([7, 2])
                except RuntimeError as error:
                    errors.append(error)
                else:
                    self.fail("injected report failure succeeded")
            self.assertEqual(session.token_ids, old_tokens)
            self.assertEqual(tuple(session._pages), old_pages)
            self.assertEqual(self.records(session), old_records)
            self.assertEqual(session.report(), old_report)
            self.assert_pages_released(references)
            session.append([7, 2])
            self.assertEqual(session.token_ids, old_tokens + (7, 2))
        self.assertEqual(len(errors), 1)

    def test_checksum_failure_preserves_committed_cache_for_append_and_replacement(self):
        errors = []
        for replace in (False, True):
            with self.subTest(replace=replace), self.session(page_tokens=1) as session:
                session.prefill([1, 3, 5])
                before, report, tokens = self.records(session), session.report(), session.token_ids
                damaged, original = self.corrupt_second_layer()
                try:
                    try:
                        (session.prefill if replace else session.append)([7, 2])
                    except ValueError as error:
                        errors.append(error)
                    else:
                        self.fail("corrupted checkpoint accepted")
                finally:
                    damaged.write_bytes(original)
                self.assertEqual((self.records(session), session.report(), session.token_ids), (before, report, tokens))
                session.decode(4)
        self.assertEqual(len(errors), 2)

    def test_reset_and_close_release_mixed_pages_and_allow_fresh_prefill(self):
        with self.session(page_tokens=1) as session:
            session.prefill([1, 3, 5, 7])
            references = [(weakref.ref(page), weakref.ref(page.arena)) for page in session._pages]
            session.reset()
            self.assertEqual(session.token_ids, ())
            self.assertEqual(session.resident_page_count, 0)
            self.assert_pages_released(references)
            session.prefill([2])
            self.assertEqual(self.codecs(session), ["f32"])
            references = [(weakref.ref(page), weakref.ref(page.arena)) for page in session._pages]
        session.close()
        self.assert_pages_released(references)

    def test_cli_reports_age_policy_and_rejects_incompatible_codec_flags(self):
        command = [sys.executable, str(ROOT / "tools/nexa_run.py"), str(self.path), "--tokens", "1,3,5",
                   "--decode-tokens", "7", "--kv-cache", "--kv-page-tokens", "1", "--kv-policy", "age",
                   "--kv-hot-pages", "1", "--kv-warm-pages", "1", "--kv-group-size", "3",
                   "--prefill-chunk-size", "2", "--memory-budget", "1MiB", "--max-sequence-length", "8"]
        result = subprocess.run(command, capture_output=True, text=True, timeout=60)
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads(result.stdout)
        self.assertEqual(report["kv_policy"]["policy_id"], "CPU_PAGE_AGE_F32_Q4_Q3_V1")
        self.assertEqual(report["token_ids"], [1, 3, 5, 7])
        self.assertFalse(report["validation"]["verified"])
        for extra in (["--kv-codec", "q4"], ["--kv-codec", "tq"], ["--kv-bits", "3"],
                      ["--kv-hot-pages", "0"], ["--kv-warm-pages", "-1"]):
            with self.subTest(extra=extra):
                failed = subprocess.run(command + extra, capture_output=True, text=True, timeout=60)
                self.assertNotEqual(failed.returncode, 0)
                self.assertNotIn("Traceback", failed.stderr)


@unittest.skipUnless(torch_available(), "Optional PyTorch reference is unavailable")
class TieredOracleRegressions(_TierFixture):
    def test_native_matches_chunk_aware_oracle_for_heads_pages_and_policy_thresholds(self):
        cases = ((1, 2, 2, False, 1, 1, 1, 3), (2, 4, 1, True, 2, 1, 0, 5),
                 (2, 4, 2, False, 3, 2, 1, 3))
        for index, (layers, heads, kv_heads, tied, page, hot, warm, group) in enumerate(cases):
            path = self.directory / f"case-{index}"
            random_bundle(path, layers=layers, heads=heads, kv_heads=kv_heads, tied=tied, seed=1701 + index)
            config, weights = load_bundle_weights(path)
            oracle = TorchTieredReference(config, weights, page_tokens=page, hot_pages=hot,
                                           warm_pages=warm, group_size=group)
            with self.subTest(case=index), self.session(path, page_tokens=page, hot_pages=hot,
                                                       warm_pages=warm, kv_group_size=group) as session:
                for index, chunk in enumerate(([1, 4, 2], [6], [8, 3, 5])):
                    actual = (session.prefill if index == 0 else session.append)(chunk)
                    expected = (oracle.prefill if index == 0 else oracle.append)(chunk)
                    self.assertTrue(compare_logits(actual, expected)["passed"])
                    self.assertEqual(self.codecs(session), list(oracle.page_codecs))
                for (layer, kind, position, head), (codec, row) in self.records(session).items():
                    if codec == "f32":
                        decoded = struct.unpack("<" + "f" * config.head_dim, row)
                    else:
                        decoded = (decode_q4_row if codec == "q4" else decode_q3_row)(row, config.head_dim, group)
                    self.assert_rows_close([decoded], [oracle._cache[layer][kind][position, head].tolist()])
                self.assertTrue(compare_logits(session.prefill([2, 6]), oracle.prefill([2, 6]))["passed"])
                self.assertEqual(session.token_ids, (2, 6))
                self.assertEqual(self.codecs(session), list(oracle.page_codecs))

    def test_verifier_replays_chunks_and_separates_execution_weight_kv_and_combined_errors(self):
        source, path = self.tiny_bundle()
        options = TIERED_GOLDEN["options"]
        result = verify_tiered_bundle_forward(path, TIERED_GOLDEN["token_chunks"], TIERED_GOLDEN["logits"],
                                              source_dir=source, **options)
        self.assertTrue(result["verified"])
        self.assertEqual(result["reference"], "pytorch_decoded_q4_kv_age_tiers")
        for name, expected in TIERED_GOLDEN["error_max"].items():
            self.assertNotIn("passed", result[name])
            self.assertAlmostEqual(result[name]["max_abs_error"], expected, places=7)
        no_source = verify_tiered_bundle_forward(path, TIERED_GOLDEN["token_chunks"], TIERED_GOLDEN["logits"], **options)
        self.assertIsNone(no_source["quantization_error"])
        self.assertNotIn("combined_quantization_error", no_source)
        wrong_history = verify_tiered_bundle_forward(path, [[1, 3, 5, 7]], TIERED_GOLDEN["logits"], **options)
        self.assertFalse(wrong_history["verified"])
        for chunks in ([], [[]], [None], "1,3"):
            with self.assertRaises(ValueError):
                verify_tiered_bundle_forward(path, chunks, TIERED_GOLDEN["logits"], **options)

    def test_cli_verification_uses_actual_prefill_chunk_and_decode_history(self):
        source, path = self.tiny_bundle()
        command = [sys.executable, str(ROOT / "tools/nexa_run.py"), str(path), "--tokens", "1,3,5",
                   "--decode-tokens", "7", "--kv-cache", "--kv-page-tokens", "1", "--kv-policy", "age",
                   "--kv-hot-pages", "1", "--kv-warm-pages", "1", "--kv-group-size", "3",
                   "--prefill-chunk-size", "2", "--memory-budget", "1MiB", "--verify",
                   "--reference-checkpoint", str(source)]
        result = subprocess.run(command, capture_output=True, text=True, timeout=60)
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads(result.stdout)
        self.assertTrue(report["validation"]["verified"])
        self.assertEqual(report["validation"]["token_chunks"], [[1, 3], [5], [7]])
        self.assertEqual(report["validation"]["reference"], "pytorch_decoded_q4_kv_age_tiers")
        for name in ("quantization_error", "kv_quantization_error", "combined_quantization_error"):
            self.assertNotIn("passed", report["validation"][name])


if __name__ == "__main__":
    unittest.main()
